config/routes.rb
Rails.application.routes.draw do
  resources :products

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :products, through: :categorizations
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :publisher
  has_many :categorizations
  has_many :categories, through: :categorizations
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("name")
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, notice: "Successfully created product."
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: "Successfully updated product."
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: "Successfully destroyed product."
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RcSimpleformdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

    <% if @product.errors.any? %>
        <div class="error_messages">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>

    <div class="field">
      <%= f.label :released_on %><br />
      <%= f.date_select :released_on %>
    </div>

    <div class="field">
      <%= f.check_box :discontinued %>
      <%= f.label :discontinued %>
    </div>

    <div class="field">
      <%= f.label :rating %><br />
      <%= f.radio_button :rating, 1 %> 1
      <%= f.radio_button :rating, 2 %> 2
      <%= f.radio_button :rating, 3 %> 3
      <%= f.radio_button :rating, 4 %> 4
      <%= f.radio_button :rating, 5 %> 5
    </div>

    <div class="field">
      <%= f.label :publisher_id %><br />
      <%= f.collection_select :publisher_id, Publisher.all, :id, :name, include_blank: true %>
    </div>

    <div class="field">
    <%= hidden_field_tag "product[category_ids][]", nil %>
    <% Category.all.each do |category| %>
        <%= check_box_tag "product[category_ids][]", category.id, @product.category_ids.include?(category.id), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name %><br />
    <% end %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<%end%>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Games</h1>

<% @products.each do |product| %>

    <div class="product">
      <h2><%= link_to product.name, product %></h2>

      <div class="details">
        <%= number_to_currency(product.price) %> |
        <%= product.categories.map(&:name).join(", ") %> |
        <%= product.publisher.name %>

      </div>
    </div>


<% end %>


<p><%= link_to "New Product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <b>Categories:</b>
  <%= @product.categories.map(&:name).join(", ") %>
</p>

<p>
  <b>Released on:</b>
  <%= @product.released_on.strftime("%B %e, %Y") %>
</p>

<p>
  <b>Publisher:</b>
  <%= @product.publisher.try(:name) %>
</p>

<p>
  <b>Rating:</b>
  <%= @product.rating %>
</p>

<p>
  <b>Discontinued:</b>
  <%= @product.discontinued ? "Yes" : "No" %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>